# Generated by Django 3.0.4 on 2020-03-25 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApplication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='email_verifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserId', models.CharField(max_length=50)),
                ('VCode', models.CharField(max_length=8)),
            ],
        ),
    ]
