# Generated by Django 3.0.4 on 2020-03-28 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApplication', '0002_email_verifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fullname',
            field=models.CharField(default='Default', max_length=255, verbose_name='Username'),
        ),
        migrations.AddField(
            model_name='user',
            name='userId',
            field=models.CharField(default=0, max_length=255, verbose_name='UserId'),
        ),
    ]
