# Generated by Django 3.0.4 on 2020-03-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApplication', '0003_auto_20200328_0031'),
    ]

    operations = [
        migrations.DeleteModel(
            name='email_verifier',
        ),
        migrations.DeleteModel(
            name='user_register',
        ),
        migrations.RemoveField(
            model_name='user',
            name='userId',
        ),
        migrations.AddField(
            model_name='user',
            name='securitycode',
            field=models.CharField(default='', max_length=8),
            preserve_default=False,
        ),
    ]
